### ISSUE TITLE
searchDmsObjects wrong url when using categories

### ISSUE THREAD

**Issue by developerCgerbsch** [d-velop/dvelop-sdk-node#146]
When using the searchDmsObject method with _categories_ parameter I get the following error: "Unable to parse json for 'sourcecategories'". 
I found out that the URL Parameter _sourcecategories_ does not look as expected: https://test-tenant.d-velop.de/dms/r/23c8bf82-f4b2-489a-9656-6cbfdc27ae3d/srm?sourceid=mySourceId&sourceproperties={"name":["testcger"]}&sourcecategories[]=TESTCAT 

Maybe this will help: https://stackoverflow.com/questions/49944387/how-to-correctly-use-axios-params-with-arrays

**Comment by LenKlose** [comment]
Hi @developerCgerbsch,
thanks for reporting!

We deployed a fix that will hit latest soon. If you want you can test by installing the next version via
```bash
npm i @dvelop-sdk/dms@next
```
