### ISSUE TITLE
Update Axios

### ISSUE THREAD

**Issue by mcremer-able** [d-velop/dvelop-sdk-node#163]
Axios is in the latest release on version `1.3.4`
The project uses version `0.23` from *Sep 4, 2021*

Aside from the obvious security risk, this also causes issues with libaries that use axios `>=1.0`

**Comment by LenKlose** [comment]
Hi @mcremer-able,

we could not find any security risks in our current axios version. If you have contradicting information please let us know.

But you're obviously right in the fact that our axios version is outdated. We will look into the effort needed.

Thanks for your contribution.

Lennart
