### ISSUE TITLE
Users and Groups for Identityprovider-App

### ISSUE THREAD

**Issue by Patrick-Rose-dev** [d-velop/dvelop-sdk-node#18]
- Scim users with optional filter
- Scim users with id
- Scim groups with optional filter
- Scim groups with id
- Interfaces for groups and single group with members
- Extend interface for users

https://developer.d-velop.de/documentation/idpapi/de/identityprovider-app-201523580.html#IdentityproviderApp-VerwendendesSCIM-ProtokollszurAuthentifizierung

**Comment by LenKlose** [comment]
Hi Patrick,

thanks for contributing to the project. Looking at the requested features and the [Identityprovider-App](https://developer.d-velop.de/documentation/idpapi/en/identityprovider-app-201523580.html) it seems the following changes would be most in line with the current state of the project:

* Extension of the ScimUser and moving it up a level for access
* Creating a ScimGroup interface
* A getUsers function
  ```typescript
  function getUsers(systenBaseUri: string, authSessionId: string, ...): ScimUser[] {
    // GET /identityprovider/scim/Users
    // GET /identityprovider/scim/Users?filter=DisplayName%20co%20Smith
  }
  ```

* A getUser function
  ```typescript
  function getUser(systenBaseUri: string, authSessionId: string, ...): ScimUser {
    // GET /identityprovider/scim/Users/2b04bb70-10fa-4892-a62a-97627f0fc67f
    // GET /identityprovider/scim/Users/2b04bb70-10fa-4892-a62a-97627f0fc67f?detailLevel=1
  }
  ```

* A getGroups function
  ```typescript
  function getGroups(systenBaseUri: string, authSessionId: string, ...): ScimGroup[] {
    // GET /identityprovider/scim/Groups
  }
  ```
* A getGroup function
  ```typescript
  function getGroup(systenBaseUri: string, authSessionId: string, ...): ScimGroup {
    // GET /identityprovider/scim/Groups/3399e87a-32d5-4db5-a934-1c3e285d7e71
  }
  ```

Key questions are going to be:
* How are you going to handle paging within the API?
* How are you going to handle filtering?
* How are you going to handle the detailLevel parameter?

We are looking forward to your contributions :)

**Comment by LenKlose** [comment]
Closed due to inactivity. Please comment to reopen.
