### ISSUE TITLE
on-prem support

### ISSUE THREAD

**Issue by GottZ** [d-velop/dvelop-sdk-node#200]
hello there.
today I've started digging a little into the source of this repository and noticed a ton of overlap with on-prem installations of D3, just requiring some header injections and slight changes inside some Adapters and Middleware, to just make it work behind the d.ecs http gateway.
due to the fact the required changes are fairly minimal core changes, I wonder if anyone thought about giving support for fully licensed on-prem current environments.

if there ain't any plans for that, and nothing is available for doing so, I'll just port this SDK myself, as the license doesn't forbid it.

**Comment by ckuetbach** [comment]
hello @GottZ 

you are right, there is a huge overlap between the on-prem installation and the cloud version, as most applications are the same. 

If you take a quick look into the C# pendent you'll see, that there is a fallback for a pre-configured system-base URI and a default tenant-id: https://github.com/d-velop/dvelop-sdk-cs/blob/main/dvelop-sdk-tenant/TenantMiddleware/TenantMiddleware.cs#L105

This fallback is only used if both header are absent, because of security reasons.

The same behavior could be adopted here:
https://github.com/d-velop/dvelop-sdk-node/blob/main/packages/express-utils/src/middleware/dvelop-context-middleware/dvelop-context-middleware.ts#L26

Or you create a middleware which creates a dvelopContext like so:
```
export function contextMiddleware(
  req: Request,
  _: Response,
  next: NextFunction
): void {
  const onPremHost = "https://mydomain.local";
  const onPremTenantId = "0";

  req.dvelopContext = {
    systemBaseUri: onPremHost,
    tenantId: onPremTenantId,
    requestId: undefined,
    requestSignature: undefined,
  };
  next();
}
```

So I think the SDK can already easily be used on Prem. The main issue is, that there may be incompatibilities because of older version, which may be found at on-premises systems.

@LenKlose What do you think? Would injecting headers or a default base-uri or tenant-id like in the C# version a better approach?

**Comment by LenKlose** [comment]
Hello @GottZ,

are we only talking about the express-middleware (the [contextMiddleware](https://github.com/d-velop/dvelop-sdk-node/blob/248aa16e6ea9255beebf728142341a3c027f2bf4/packages/express-utils/src/middleware/dvelop-context-middleware/dvelop-context-middleware.ts#L66))? I think it would be reasonable to add a way to add custom values or supply a secondary context middleware function.

**Comment by ckuetbach** [comment]
Hi,

that looks promising. The important part is, that you don't use a user-provided `x-dv-baseuri` without verifying `x-dv-sig1`.

As you always hardcode your base-uri this approach would be fine (from a security perspective) as long as you don't include the middleware to verify the signature.

The only downside I can see right now is, that we may decide to make the check for `x-dv-sig1` mandatory if a `x-dv-baseuri` within the SDK-provided `contextMiddleware`. 

In that case you could use a self written `contextMiddleware` which only sets the `dvelopContext` or create the signature yourself .


> so far I'd say it would help a ton, if I could provide a custom DvelopHttpRequestConfig to the sdk for use in the _defaultHttpRequestFunctionFactory.

I'm not completely sure about this topic, the user-object is written into the requestcontext through another middleware. But I have to admit, that I'm not deep into the node-sdk to know for sure how they work together.

I would expect that everythig works fine with your code as long as you also include the authenticationMiddleware https://github.com/d-velop/dvelop-sdk-node/blob/248aa16e6ea9255beebf728142341a3c027f2bf4/packages/express-utils/src/middleware/dvelop-authentication-middleware/dvelop-authentication-middleware.ts#L73

**Comment by GottZ** [comment]
> As you always hardcode your base-uri this approach would be fine (from a security perspective) as long as you don't include the middleware to verify the signature.

ip pinning ftw. I don't let any other client but the http gateway make calls to the module.

> The only downside I can see right now is, that we may decide to make the check for `x-dv-sig1` mandatory if a `x-dv-baseuri` within the SDK-provided `contextMiddleware`.

would be reasonable to have a instance initialization construct then.

> In that case you could use a self written `contextMiddleware` which only sets the `dvelopContext` or create the signature yourself.

true.

> > so far I'd say it would help a ton, if I could provide a custom DvelopHttpRequestConfig to the sdk for use in the _defaultHttpRequestFunctionFactory.
> 
> I'm not completely sure about this topic, the user-object is written into the requestcontext through another middleware. But I have to admit, that I'm not deep into the node-sdk to know for sure how they work together.
> 
> I would expect that everythig works fine with your code as long as you also include the authenticationMiddleware

apparently it doesn't take the CA from the system certificate store, so I have to override axum's http configuration to provide the certificate manually.
right now I'm not running it on the same machine as d3 itself. in that case, it would likely work.
we have a messy DMZ structure thanks to kdvz requirements and demands, to get our server connected to other api's.

that's precisely what I'm debugging and tinkering with right now. who knows.. maybe it's also client OS configuration related. I have to find the cause myself.

**Comment by GottZ** [comment]
ok so apparently that certification issue I noticed is actually common.
https://github.com/nodejs/node/issues/4175

nodejs on windows doesn't use the windows certificate store at all, thus tools like https://github.com/ukoloff/win-ca or  similar have to be used, in order to use custom certificates in nodejs for windows..
noticing the age of win-ca, I'll definitely do further digging and tell you about it.. (unless you already have an idea in mind, outside just adding the crt manually to https.globalAgent.options.ca)

**Comment by LenKlose** [comment]
Hey @GottZ 

could you take a look at #202 and see if this would solve your problem?

This would enable you to initilaze your middleware like this:

```typescript
import { contextMiddlewareFactoryWithFixedSystemBaseUri } from "@dvelop-sdk/express-utils";

app.use(contextMiddlewareFactoryWithFixedSystemBaseUri("https://my.local.baseuri")); //could optionally supply a tenantId (default: 0)

app.use((req: Request, _: Response, next: NextFunction) => {
  console.log(req.dvelopContext);
  next();
});
```

**Comment by GottZ** [comment]
that's looking great and indeed reduces code-smell! nice
